id: P009394
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:36:41.918819
source_metadata:
  id: bdr:W3CN5390
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་སྔོན་འགྲོའི་འབུམ་ལྔ་བསགས་སྐབས་ཀྱི་ཟིན་བྲིས་འགའ་ཞིག
  author: ''
  volumes:
    d40cfcda70fd46a4bc3b37ccb324508d:
      image_group_id: I3CN5392
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
